# Site settings
title: "Waqar Ahmed - AI & High-Performance Computing"
description: "Exploring AI optimization, GPU acceleration, and computer vision. Sharing research insights, practical learnings, and hands-on experiences from making AI work in the real world—from domain adaptation to production ML systems."
baseurl: ""
url: "https://waqarahmed89.github.io"
author:
  name: "Waqar Ahmed"
  title: "AI Researcher & High-Performance Computing Specialist"
  organization: "AMD"
  email: "waqarahmed4544@gmail.com"
  linkedin: "https://www.linkedin.com/in/waqarahmed1989/"
  github: "https://github.com/waqarahmed89"
  scholar: "https://scholar.google.com/citations?user=2I-M3S0AAAAJ&hl=en&oi=ao"
  location: "Global"
  
# SEO and Social
keywords: "AI, machine learning, GPU computing, computer vision, high-performance computing, CUDA, deep learning, domain adaptation, neural networks, AMD"
twitter_username: ""
social:
  name: "Waqar Ahmed"
  links:
    - https://www.linkedin.com/in/waqarahmed1989/
    - https://github.com/waqarahmed89
    - https://scholar.google.com/citations?user=2I-M3S0AAAAJ&hl=en&oi=ao

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Default YAML front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Waqar Ahmed"
  - scope:
      path: ""
    values:
      layout: default

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor/

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true